version: '2.2'
services:
    gym-duckietown-ros:
        image: duckietown/gym-duckietown-ros-agent
        command: /bin/bash -c "./agent/run_display.bash &&
                               source dt_msg_ws/devel/setup.bash && 
                               /usr/bin/python agent/rosagent.py"
        depends_on:
        - "lanefollow"
        volumes:
        - .:/workspace/agent/
        networks:
        - gym-duckietown-net
        environment:
        - "ROS_MASTER_URI=http://lanefollow:11311"
        - "DUCKIETOWN_SERVER=gym-duckietown-server"
        - "HOSTNAME=default"
        - "DISPLAY=:99"
        - "DUCKIETOWN_CHALLENGE=LF"
        expose:
        - "8902"
        - "5558"
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        ports:
        - "8902:8902"
        - "5558:5558"

    lanefollow:
        build: 
            context: .
            dockerfile: DockerfileCatkin
        networks:
        - gym-duckietown-net
        command: /bin/bash -c  "source /home/software/docker/env.sh && 
                                ./set_vehicle_name.sh && 
                                source /home/software/custom_ws/devel/setup.bash && 
                                roslaunch lf_slim.launch"
        entrypoint:
        - "qemu3-arm-static"
        environment:
        - "ROS_MASTER_URI=http://lanefollow:11311"
        - DUCKIETOWN_SERVER=gym-duckietown-server
        - "HOSTNAME=default"
        cpu_count: 2
        cpu_percent: 50
        cpus: 0.5
      


networks:
  gym-duckietown-net:
